import { AuthProvider } from "./context/AuthContext";
import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ShopifyFR",
  description: "Generated by ShopifyFR",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>ShopifyFR</title>
        <meta name="description" content="Generated by ShopifyFR" />
        <link rel="icon" href="/logo.png" />
      </head>
      <body>
        <AuthProvider>
          {children}
          <Analytics/>
        </AuthProvider>
      </body>
    </html>
  );
}
